#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import secrets
import shutil
import subprocess
import textwrap
import time
import tomllib
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PYPROJECT_PATH = ROOT / "pyproject.toml"
FORMULA_PATH = ROOT / "Formula" / "nanobot.rb"
FORMULA_CLASS = "Nanobot"
PACKAGE_NAME = "nanobot-ai"
FORMULA_NAME = "nanobot"
HOMEPAGE = "https://github.com/HKUDS/nanobot"
DESC = "Local-first assistant control plane for chat, cron, and agent automation"
LICENSE = "MIT"
PYTHON_FORMULA = "python@3.13"
SOURCE_WAIT_SECONDS = 300
SOURCE_WAIT_INTERVAL_SECONDS = 15
EXCLUDED_RESOURCES = {"hf-xet"}
REQUIRED_RESOURCES = {"agent-client-protocol"}


@dataclass(frozen=True)
class SourceArtifact:
    version: str
    url: str
    sha256: str


def normalize_version(version: str) -> str:
    return version[1:] if version.startswith("v") else version


def project_version(pyproject_path: Path = PYPROJECT_PATH) -> str:
    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    return str(data["project"]["version"])


def fetch_pypi_release_payload(package_name: str, version: str) -> dict:
    url = f"https://pypi.org/pypi/{package_name}/{version}/json"

    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            return json.load(response)
    except urllib.error.HTTPError as exc:
        raise RuntimeError(
            f"Unable to fetch PyPI metadata for {package_name} {version}: HTTP {exc.code}"
        ) from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(
            f"Unable to fetch PyPI metadata for {package_name} {version}: {exc}"
        ) from exc


def select_sdist(payload: dict, version: str) -> SourceArtifact:
    urls = payload.get("urls", [])
    for artifact in urls:
        if artifact.get("packagetype") == "sdist":
            return SourceArtifact(
                version=version,
                url=str(artifact["url"]),
                sha256=str(artifact["digests"]["sha256"]),
            )

    raise RuntimeError(f"No source distribution found for nanobot-ai {version}")


def fetch_source_artifact(package_name: str, version: str) -> SourceArtifact:
    payload = fetch_pypi_release_payload(package_name, version)
    return select_sdist(payload, version)


def indent_resource_block(resource_block: str) -> str:
    stripped = resource_block.strip()
    if not stripped:
        return "  # Resource stanzas are generated by scripts/update_homebrew_formula.py"
    normalized_lines = []
    for line in textwrap.dedent(stripped).splitlines():
        normalized_lines.append(line[2:] if line.startswith("  ") else line)
    return "\n".join(f"  {line}" if line else "" for line in normalized_lines)


def filter_resource_block(resource_block: str) -> str:
    filtered = resource_block
    for resource_name in EXCLUDED_RESOURCES:
        filtered = re.sub(
            rf'^\s*resource "{re.escape(resource_name)}" do\n(?:\s+.*\n)*?\s*end\n?',
            "",
            filtered,
            flags=re.MULTILINE,
        )
    return filtered.strip()


def lock_packages(lock_path: Path = ROOT / "uv.lock") -> dict[str, dict]:
    data = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    return {pkg["name"]: pkg for pkg in data["package"]}


def build_resource_block(name: str, package: dict) -> str:
    artifact = package.get("sdist") or (package.get("wheels") or [None])[0]
    if not artifact:
        raise RuntimeError(f"No distributable artifact available for resource {name}")

    digest = artifact["hash"]
    if digest.startswith("sha256:"):
        digest = digest.split(":", 1)[1]

    return "\n".join(
        [
            f'resource "{name}" do',
            f'    url "{artifact["url"]}"',
            f'    sha256 "{digest}"',
            "  end",
        ]
    )


def ensure_required_resources(resource_block: str, required_resources: set[str]) -> str:
    packages = lock_packages()
    blocks = [resource_block.strip()] if resource_block.strip() else []

    for name in sorted(required_resources):
        if re.search(rf'^\s*resource "{re.escape(name)}" do$', resource_block, flags=re.MULTILINE):
            continue
        if name not in packages:
            raise RuntimeError(f"Required Homebrew resource {name} missing from uv.lock")
        blocks.append(build_resource_block(name, packages[name]))

    return "\n\n".join(block for block in blocks if block).strip()


def render_formula(source: SourceArtifact, resource_block: str) -> str:
    resources = indent_resource_block(resource_block)
    lines = [
        f"class {FORMULA_CLASS} < Formula",
        "  include Language::Python::Virtualenv",
        "",
        f'  desc "{DESC}"',
        f'  homepage "{HOMEPAGE}"',
        f'  url "{source.url}"',
        f'  sha256 "{source.sha256}"',
        f'  license "{LICENSE}"',
        "",
        '  depends_on "rust" => :build',
        '  depends_on "libxml2"',
        '  depends_on "libxslt"',
        '  depends_on "libyaml"',
        f'  depends_on "{PYTHON_FORMULA}"',
        "",
        *resources.splitlines(),
        "",
        "  def install",
        "    virtualenv_install_with_resources",
        "  end",
        "",
        "  def post_install",
        '    (var/"nanobot").mkpath',
        "  end",
        "",
        "  service do",
        '    run [opt_bin/"nanobot", "gateway"]',
        "    keep_alive true",
        '    working_dir var/"nanobot"',
        '    log_path var/"log/nanobot-gateway.log"',
        '    error_log_path var/"log/nanobot-gateway.log"',
        "  end",
        "",
        "  def caveats",
        "    <<~EOS",
        "      Run `nanobot onboard` before starting the service so `~/.nanobot/config.json` exists.",
        "",
        "      Start the gateway with:",
        f"        brew services start {FORMULA_NAME}",
        "",
        "      Repo deploys only update the tap. Each machine still needs a local refresh such as:",
        f"        brew update && brew upgrade {FORMULA_NAME} && brew services restart {FORMULA_NAME}",
        "",
        "      If you manage services through Homebrew Bundle, `restart_service: :changed` can restart the",
        "      gateway after the local bundle apply.",
        "    EOS",
        "  end",
        "",
        "  test do",
        '    output = shell_output("#{bin}/nanobot --help")',
        '    assert_match "Usage", output',
        "  end",
        "end",
    ]
    return "\n".join(lines) + "\n"


def temp_tap_name() -> str:
    return f"nanobot/temp-{secrets.token_hex(4)}"


def create_temp_tap() -> tuple[str, Path]:
    tap_name = temp_tap_name()
    subprocess.run(
        ["brew", "tap-new", "--no-git", tap_name], check=True, capture_output=True, text=True
    )
    result = subprocess.run(
        ["brew", "--repository", tap_name],
        check=True,
        capture_output=True,
        text=True,
    )
    return tap_name, Path(result.stdout.strip())


def cleanup_temp_tap(tap_name: str, tap_path: Path) -> None:
    subprocess.run(["brew", "untap", tap_name], check=False, capture_output=True, text=True)
    shutil.rmtree(tap_path, ignore_errors=True)


def refresh_resource_block(
    formula_path: Path, version: str, package_name: str = PACKAGE_NAME
) -> str:
    tap_name, tap_path = create_temp_tap()
    source = fetch_source_artifact(package_name, version)

    try:
        temp_formula_path = tap_path / "Formula" / formula_path.name
        temp_formula_path.parent.mkdir(parents=True, exist_ok=True)
        temp_formula_path.write_text(render_formula(source, ""), encoding="utf-8")

        command = [
            "brew",
            "update-python-resources",
            "--print-only",
            "--package-name",
            package_name,
            "--version",
            version,
            str(temp_formula_path),
        ]
        result = subprocess.run(command, check=True, capture_output=True, text=True)
    finally:
        cleanup_temp_tap(tap_name, tap_path)

    filtered = filter_resource_block(result.stdout)
    return ensure_required_resources(filtered, REQUIRED_RESOURCES)


def wait_for_source_artifact(package_name: str, version: str, wait_seconds: int) -> SourceArtifact:
    attempts = max(1, wait_seconds // SOURCE_WAIT_INTERVAL_SECONDS + 1)
    last_error: RuntimeError | None = None

    for _ in range(attempts):
        try:
            return fetch_source_artifact(package_name, version)
        except RuntimeError as exc:
            last_error = exc
            if wait_seconds <= 0:
                break
            time.sleep(SOURCE_WAIT_INTERVAL_SECONDS)

    assert last_error is not None
    raise last_error


def update_formula(
    formula_path: Path = FORMULA_PATH,
    version: str | None = None,
    package_name: str = PACKAGE_NAME,
    refresh_resources: bool = True,
    wait_seconds: int = SOURCE_WAIT_SECONDS,
) -> Path:
    resolved_version = normalize_version(version or project_version())
    source = wait_for_source_artifact(package_name, resolved_version, wait_seconds)
    resource_block = ""
    if refresh_resources:
        resource_block = refresh_resource_block(formula_path, resolved_version, package_name)

    formula_path.parent.mkdir(parents=True, exist_ok=True)
    formula_path.write_text(render_formula(source, resource_block), encoding="utf-8")
    return formula_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the Homebrew formula for nanobot.")
    parser.add_argument(
        "--version", help="Package version or tag to generate, defaults to pyproject"
    )
    parser.add_argument(
        "--formula-path",
        type=Path,
        default=FORMULA_PATH,
        help="Path to write the generated formula to",
    )
    parser.add_argument(
        "--package-name",
        default=PACKAGE_NAME,
        help="PyPI package name to resolve for source metadata and resources",
    )
    parser.add_argument(
        "--skip-resource-refresh",
        action="store_true",
        help="Write the formula without regenerating Homebrew resource stanzas",
    )
    parser.add_argument(
        "--wait-seconds",
        type=int,
        default=SOURCE_WAIT_SECONDS,
        help="Seconds to wait for the version to appear on PyPI before failing",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    path = update_formula(
        formula_path=args.formula_path,
        version=args.version,
        package_name=args.package_name,
        refresh_resources=not args.skip_resource_refresh,
        wait_seconds=args.wait_seconds,
    )
    print(f"Updated {path}")


if __name__ == "__main__":
    main()
